### ISSUE TITLE
'=' key for spreadsheets formulas [feature request]

### ISSUE THREAD

**Issue by hubyhuby** [theolizard/remote-numpad#10]
While using the remote numpad, I found it could be convenient to have the '=' key on the numpad.
The "enter" key that si available is perfect in excel to validate, but when you want to define a formula you start with "="
Eventually the arrow "up" "down" "left" "right" could be nice.

Thks for this life saving app ! I just got a 13inch laptop without a numpad. And this is very anoying when doing lot of calculations on libre office. It works great in HID mode under Ubuntu Mate 22.04
Design idea
![image](https://user-images.githubusercontent.com/26340942/181815413-7f0fab9d-8a0c-4db4-bb2e-2d1974c70676.png)

**Comment by Jcaiken** [comment]
I support the suggestion of splitting the '+' key in two and adding the '=' symbol. 
I would also suggest adding the Enter symbol instead of text.

**Comment by theolizard** [comment]
It has been done :)
