### ISSUE TITLE
Problems connecting as HID device

### ISSUE THREAD

**Issue by xandro0777** [theolizard/remote-numpad#11]
Hi, I wanted to use one Android device as input device for another one - I assume this would only work with the Bluetooth HID method?

Well I tried various things, it looks the closest I was able to get at it was pairing the devices vie Android Bluetooth settings, then selecting the other device as host. Tapped "PAIR", not sure if it did anything but it left the settings menu. Then tapped "connect" which did apparently succeed but after tapping any other key (like "1") it was immediately disconnected.

Unfortunately, when I tried to reproduce it with cable and adb logcat attached it did not work anymore :(

Any idea what I am doing wrong?

BTW my actual usecase would be to emulate a  BT mouse or touchpad which should not be too hard to add to the code if I get the connection working .. waht do you think?

TIA

**Comment by theolizard** [comment]
Hello, the HID connection process has been updated. I suggest you try unpairing the devices and use the pair button in the app to create the pairing. It _should_ work now. Please keep me informed.

**Comment by brandsimon** [comment]
After a bit of testing these steps worked very well for me (Android to Android, Android to Windows)
- open system Bluetooth on both devices and press add new device, but don't add a device. This step makes both devices visible, the in-app pair dialog did not open if nothing is visible.
- use the in-app pair dialog to pair
- change setting of device to connect to (probably it makes sense to change this automatically after a fresh pairing?)
- press connect

Android to Linux connection did not work for me. When I tried to pair, there was no pairing dialog. So I tried to pair over system dialog. I cancelled when I was asked for a pin, then immediately tried to pair over the app, which worked fine, but when I pressed connect, it did not connect. A real Bluetooth keyboard works fine on the Linux PC. Do you have any hints?

**Comment by theolizard** [comment]
Ok! I confirm it does not work on Linux. I will work on it as soon as I can.

**Comment by brandsimon** [comment]
@theolizard

Thank you very much!

**Comment by jolinux** [comment]
Hello 
you fix HiD-Pairing version 2.07 and 2.08/09. But the problem pairing and connect BT Linux-Host is not working !

jo

**Comment by theolizard** [comment]
Hello,
Did you try to unpair and re-pair using the app? The old pairings are not compatible with the latest version.
Kind regards,

**Comment by jolinux** [comment]
Hello,
pair or un-pair with the app I found no way. The app has a button PAIR menu settings. This button has no effect.
I do: Smartphone system-function BT delete the connect and unpair before.  Hope your app can new pair but this not work because no feedback so I use the system-function pair. 

After this doing, I use your app menu setting by the new host (Linux) and connect the phone with the connecting button by the remote-numpad-app.  Waiting of connection ....  and after any key press "connection lost"  => Error !

jo

**Comment by theolizard** [comment]
It may take a few seconds for the pairing dialog to show up after pressing the PAIR button in the app. It only shows up once it finds at least one device to list. The app definitely will not work if the pairing is not done using that button.

It works for me with a Samsung Galaxy S7 and an Ubuntu host. Unpair on either side or both sides (in the device settings), make sure the host is visible (keep Bluetooth settings open on host), tap PAIR in the app (may need to wait a bit), then select the host in the dialog that pops up and follow instructions.

If that does not work, I guess I am unable to replicate.

**Comment by theolizard** [comment]
I will close this issue as resolved. Please feel free to reopen another issue if the issue persists.

**Comment by brandsimon** [comment]
@theolizard Thank you very much, it works like a charm. :)
