### ISSUE TITLE
Chromebook compatibility

### ISSUE THREAD

**Issue by sanctimoniousape** [theolizard/remote-numpad#12]
I don't know if this is due to how Google links Android phones and Chromebooks, but I'm unable to use this as an HID device on Chromebooks.  Is there something I'm missing, or is there anything you can do to enable this?  Any suggestions would be welcome!

**Comment by theolizard** [comment]
It should work without any extra requirements. Try removing all Bluetooth pairings and use the pair button in the app to create the pairing. I will set up a Chrome OS Flex machine (the closest thing I can get to a Chromebook) to investigate on my side.

**Comment by theolizard** [comment]
We are having issues at the moment and the app does not work with any version of Linux. I will fix it as soon as I can.

**Comment by theolizard** [comment]
The latest version was tested on Ubuntu and it works. It should also work on Chromebook.

**Comment by theolizard** [comment]
I will close this issue as resolved. Please feel free to reopen another issue if the issue persists.
