### ISSUE TITLE
KDE Connect compatibility

### ISSUE THREAD

**Issue by maverick74** [theolizard/remote-numpad#13]
I establish my connections using KDE Connect.

However, I don't seem to be able to use Remote NumPad with it (as a simple keyboard... And there really isn't any great alternative to this!)

Can you add compatibility with KDE Connect?

Thanks!

**Comment by theolizard** [comment]
I am not too familiar with KDE Connect so give me some time to test it out.

**Comment by theolizard** [comment]
As per my tests, it does not seem like one can add functionalities to KDE Connect. However, you can still pair the remote numpad even if KDE Connect is already paired. I tried on Kubuntu and Bluetooth visibility had to be enabled to pair the devices, only for pairing, then it can be turned off. Then, when the pairing is done, the app will display a message warning that the configuration failed and the connection may not work, disregard that. Finally, when you connect for the first time with the app, KDE will ask if you trust the device, answer 'yes' and it worked for me.

**Comment by maverick74** [comment]
@theolizard I do not have Bluetooth on my computer.
My idea was to be able to use remote numpad as _a simple keyboard_, since KDE Connect already supports remote key introduction. 
But remote numpad does not show up as an optional "keyboard" for us to choose.
If it had the option to be considered as such by android one could choose it as keyboard and use it as such with no other changes...

Maybe that's "too much to change" (i don't have a clue about that!), but that would be the idea...

**Comment by theolizard** [comment]
After studying KDE Connect and its plugins system I understand that one cannot add functionality to KDE Connect without modifying KDE Connect itself. Unfortunately, that means that this feature is not going to be added. Sorry :( .

**Comment by maverick74** [comment]
I'm sorry. 
I'm probably not explaining well enough (english is not my mother language)...

The intention was **not** adding functionality to KDE Connect.

The intention was having a mode, on remote numpad, that would allow us to use it like a regular keyboard.
If we could use it as a keyboard, we would be able to use it in any other software (and that means we could also use it with KDE Connect)

**Comment by theolizard** [comment]
Gotcha! Unfortunately, that is still not something I plan on adding. It would be a sizeable undertaking.

**Comment by maverick74** [comment]
Yeah, i honestly didn't have a clue about the necessary code it would require. 
In my head it could go from either simply changing a variable (kind of saying: "Hey android, consider this a keyboard, listen to it's input") to something much much more heavy that would require a lot of coding.

Since it's the later, and while it would be a "nice to have" feature for me, for the times i would be using it, it for sure does not deserve the work it requires. :)

thank you for the time you took at studying this and replying to the issue! :1st_place_medal:
