### ISSUE TITLE
Landscape mode 

### ISSUE THREAD

**Issue by xmha97** [theolizard/remote-numpad#14]
Please add the landscape mode.

**Comment by theolizard** [comment]
Added landscape option in the commit 18313ff95c5ced4f854b769cf0408e68a346d6e5. Waiting for a few other features/fixes before publishing. Should publish within a week.

**Comment by xmha97** [comment]
Thanks,
I think it is disabled by default, why?

**Comment by theolizard** [comment]
Update has been published. Thank you for your patience! :)

**Comment by xmha97** [comment]
Thanks 👍
