### ISSUE TITLE
Add monochrome icon 

### ISSUE THREAD

**Issue by xmha97** [theolizard/remote-numpad#15]
Please add the themed icon.

![Screenshot_2023-02-24-00-00-45-720_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/221023944-0d4494f3-a619-4b70-a378-4a37f6b74279.jpg)

**Comment by theolizard** [comment]
I'll look into it.

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by theolizard** [comment]
Done and up on Play Store (might take a few hours).

**Comment by xmha97** [comment]
Thanks 👍
I downloaded it from GitHub.
