### ISSUE TITLE
Numlock on app overrides alphabetic keys on laptop keyboard

### ISSUE THREAD

**Issue by jgonyea** [theolizard/remote-numpad#3]
On my laptop, when I enable the numlock on the app so I can use the numbers, my laptop's keyboard enables its own number pad, which in turn disables many alphabet keys on the right side of the laptop keyboard.  Is there any way of using the app without this occuring?

Laptop: Pinebook Pro
OS: Manjaro KDE Plasma
Server version: remote-numpad-server-1.5.1-all.jar
App version: 1.6.3 installed via FDroid

**Comment by theolizard** [comment]
Hi,

Sorry but no, this app is designed to mimic the Numpad as closely as possible so when you press the num lock key, it will perform the num lock as if it were a physical keyboard. The num lock is done on the OS level so all the keyboards are affected.
