### ISSUE TITLE
Change Keymap

### ISSUE THREAD

**Issue by jolinux** [theolizard/remote-numpad#8]
Hello, nice tool.

where can I change the key-function ?   I use/need a keypad without the dot-Key (key_label_decimal). But I need the backspace-function without to change the settings (because reconnect and scan the network + check the host-name).  Has the dot-key a second level function after press numlock-key ?  Any chance to remap the second-function of the dot-key ?    I found no defintion of  the keystroke-mapping.  

 Have you a example of code to define a new/remapped key-id of the sec. level-dot-key ?

**Comment by hubyhuby** [comment]
I am new there, but it seems to be around this xml.
Might try to find it in the live running app...
https://github.com/theolizard/remote-numpad/blob/master/app/src/main/res/layout/content_numpad.xml

**Comment by theolizard** [comment]
The backspace function does not require disconnecting anymore. Is that OK?

**Comment by theolizard** [comment]
I will close this issue as resolved. Please feel free to reopen another issue if you have more feedback.
